version: "3.7"

volumes:
  orderer.example.com:

networks:
  supply_chain_carbon:
    name: supply_chain_carbon
    external: true

services:
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
    working_dir: /root
    command: orderer
    volumes:
      - ../../channel-artifacts/carbonchannel.block:/var/hyperledger/orderer/orderer.carbonchannel.block
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/orderer/msp
      - ../../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/etc/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - supply_chain_carbon
